#!/bin/bash

# ---------------------------------------------- 
# forc
#
# Contoh penggunaan for untuk memperoleh
#    nama-nama parameter posisi
# ----------------------------------------------

i=0

for parameter
do
  ((i=i+1))
  echo "$i. $parameter"
done
